# Generated by Django 4.2.7 on 2023-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='problemcontent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='probleminfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
