# Generated by Django 4.2.7 on 2023-11-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_comments_options_alter_problemcontent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizQuiz',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Comments',
        ),
        migrations.AlterModelTable(
            name='problemcontent',
            table='Problem_content',
        ),
        migrations.AlterModelTable(
            name='probleminfo',
            table='Problem_info',
        ),
        migrations.AlterModelTable(
            name='subjects',
            table='Subjects',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='User_info',
        ),
    ]
