# Generated by Django 4.2.7 on 2023-11-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_quizquiz_alter_comments_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
